# Generated by Django 5.0.2 on 2024-03-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0002_json_substance_substance_category_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='molecular_weight',
            field=models.FloatField(),
        ),
    ]
