# Generated by Django 5.0.2 on 2024-03-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0003_alter_substance_molecular_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='substance',
            name='validation_message',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='substance',
            name='category_tag',
            field=models.CharField(default='not_known', max_length=100),
        ),
        migrations.AlterField(
            model_name='substance',
            name='formular',
            field=models.CharField(default='not_known', max_length=500),
        ),
        migrations.AlterField(
            model_name='substance',
            name='inchl',
            field=models.CharField(default='not_known', max_length=500),
        ),
    ]
