# Generated by Django 5.0.2 on 2024-04-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0005_substance_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.JSONField(blank=True, default=list)),
                ('formular', models.CharField(blank=True, max_length=1000)),
                ('iupac_name', models.CharField(blank=True, max_length=1000)),
                ('smiles', models.CharField(blank=True, max_length=1000)),
                ('inchi', models.CharField(blank=True, max_length=1000)),
                ('inchi_key', models.CharField(blank=True, max_length=1000)),
                ('molecular_mass', models.FloatField(blank=True)),
                ('cas_num', models.CharField(blank=True, max_length=1000)),
                ('category', models.JSONField(blank=True, default=list)),
                ('source_url', models.CharField(blank=True, default='Pihkal', max_length=300)),
                ('source_name', models.CharField(blank=True, default='PIKHAL', max_length=200)),
                ('valid', models.BooleanField(blank=True, default=False)),
                ('last_changed_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.FloatField(blank=True, default=0.0)),
                ('details', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='json_substance',
        ),
        migrations.DeleteModel(
            name='Substance',
        ),
    ]
