# Generated by Django 5.0.2 on 2024-04-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0007_substances_deleted_alter_substances_cas_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store_exchange_json',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.JSONField(default=list)),
            ],
        ),
    ]
