# Generated by Django 5.0.2 on 2024-06-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0010_alter_store_exchange_json_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substances',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='substances',
            old_name='formular',
            new_name='formula',
        ),
        migrations.RenameField(
            model_name='substances',
            old_name='iupac_name',
            new_name='iupac_names',
        ),
        migrations.RenameField(
            model_name='substances',
            old_name='last_changed_at',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='substances',
            old_name='valid',
            new_name='validated',
        ),
        migrations.RemoveField(
            model_name='substances',
            name='source_name',
        ),
        migrations.RemoveField(
            model_name='substances',
            name='source_url',
        ),
        migrations.AddField(
            model_name='substances',
            name='source',
            field=models.JSONField(blank=True, default={'name': 'PIHKAL', 'url': ''}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='substances',
            name='cas_num',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='substances',
            name='version',
            field=models.CharField(blank=True, default='0', max_length=200),
        ),
    ]
