# Generated by Django 5.0.2 on 2024-06-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0011_rename_category_substances_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substances',
            name='details',
            field=models.JSONField(blank=True),
        ),
    ]
