# Generated by Django 5.0.2 on 2024-06-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0012_alter_substances_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substances',
            name='cas_num',
            field=models.CharField(blank=True, default='0', max_length=1000),
        ),
    ]
