# Generated by Django 5.0.2 on 2024-06-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0013_alter_substances_cas_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substances',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
